### ISSUE TITLE
Problem serializing a window.Node

### ISSUE THREAD

**Issue by sb8244** [adriantoine/enzyme-to-json#38] opened 2016-12-19 03:58 UTC
I'm going to preface this with something that I'm doing is probably horribly outside of the box for a React app.

I am using rc-tooltip but require that I mount it to a place other than `document.body`. To do this, I keep a mountNode and pass it down to tooltip users. My PropTypes looks like:

```
  mountNode: PropTypes.instanceOf(window.Node).isRequired,
```

I create a component instance with the following `mountNode` prop:

```
      mountNode={document.createElement('div')}
```

Upon doing so, I get this error from the toMatchSnapshot:

```
    TypeError: Cannot convert undefined or null to object
```

I don't believe that this error is coming directly from enzyme-to-json, but it seems something it is passing is unexpected in the snapshot? When I replaced the createElement with a string, it works but I get a PropTypes warning.

**Comment by adriantoine** [comment] 2017-02-09 11:43
Hi @sb8244, sorry for the delay! Thanks for raising the issue but I don't understand, can you provide an example repo for example? Are you sure the issue comes from `enzyme-to-json`?

**Comment by adriantoine** [comment] 2017-04-11 09:03
Hi again!
That is a duplicate of #47 and that is not an issue with `enzyme-to-json` but with `pretty-print`.

**Closed by adriantoine** 2017-04-11 09:03 UTC
Labels: bug
