### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by john-hu** [adriantoine/enzyme-to-json#47] opened 2017-02-13 08:33 UTC
Recently, we got an exception looks like:

```
    TypeError: Cannot convert undefined or null to object
      
      at Object.<anonymous> (__tests__/container/list/AccountsList.test.js:105:89)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Some people reports to enzyme at https://github.com/airbnb/enzyme/issues/750 .

**Comment by adriantoine** [comment] 2017-02-13 09:30
Hi!

Thanks for the report, can you tell me what brings the error? What's in `__tests__/container/list/AccountsList.test.js`?

**Comment by john-hu** [comment] 2017-03-21 09:02
Hi,

The line emits error is `expect(toJSON(accountList)).toMatchSnapshot();`

**Comment by adriantoine** [comment] 2017-03-21 09:03
Hi,

Can I see the whole test? I need to reproduce the issue.
Thanks

**Comment by andris-silis** [comment] 2017-04-10 19:06
Hello.
I have this issue caused by `react-sortable-hoc`'s `SortableContainer` and looking through the source I found that reason is `window` used as property.

For example:
```
const SomeComponent = () => <div someProp={window} />;

it('test', () => {
  const subject = shallow(<SomeComponent />);
  expect(subject).toMatchSnapshot();
}
```

**Comment by andris-silis** [comment] 2017-04-11 04:29
Same problem with `document` and `global`.

**Comment by adriantoine** [comment] 2017-04-11 08:44
Hi!
That's interesting, thanks for the use case @andris-silis, I'll investigate.

**Comment by andris-silis** [comment] 2017-04-11 08:46
I looked further and found out that the error is happening inside `pretty-format`'s `printComplexValue` where value's toJSON is called. 
Not sure if it is `enzyme-to-json`'s problem..

**Comment by adriantoine** [comment] 2017-04-11 08:55
Yeah I've just tested it myself, the issue is not coming from `enzyme-to-json`. I've just tried to run the `shallow` function without passing it to `expect()` and there's no error.

I think you should open an issue on: https://github.com/facebook/jest/issues, in the meantime you can try to mock the `window` object if possible.

I'm going to close this, thanks for you help @andris-silis!

**Closed by adriantoine** 2017-04-11 08:55 UTC
Labels: bug
