### ISSUE TITLE
toJson() hangs indefinitely

### ISSUE THREAD

**Issue by robinelvin** [adriantoine/enzyme-to-json#65] opened 2017-08-30 14:32 UTC
I tried switching from Jest but when I do my test never completes.

```
    it("should render a cell correctly in workflow mode", () => {
        const component = shallow(<ReactBoardCellComponent
            {...props}
        />);
        expect(toJson(component)).toMatchSnapshot();
    });

```

```
$ yarn test
yarn test v0.27.5
$ jest

 RUNS  src/components/__tests__/boardcell.test.tsx <-- Never completes
^C

```

enzyme 2.8.2
enzyme-to-json 1.5.1
jest 20.0.4

**Comment by adriantoine** [comment] 2017-09-15 10:46
Hi @robinelvin,

Sorry for the delay, I can't reproduce this bug, can you provide a small test repo?

Thank you!

**Comment by adriantoine** [comment] 2017-09-17 11:30
I'll close this for now, please comment if you can provide a repository which reproduce the issue.

Thanks!

**Closed by adriantoine** 2017-09-17 11:30 UTC
Labels: bug
