### ISSUE TITLE
Key value differing for saves

### ISSUE THREAD

**Issue by jpenna** [adriantoine/enzyme-to-json#60] opened 2017-06-19 19:50 UTC
I'm getting an error when I save the document without any modifications.
The only fact that I am saving it changes the snapshot and it returns as a "no match".

I am using `enzyme-to-json` with a `enzyme.mount` which is mounting:

```
<Provider store={store}>
    <MemoryRouter>
        <Component {...properties} />
     </MemoryRouter>
</Provider>
```

`Component` is a wrapped `redux-form` container:

```
reduxForm({
  form: 'myForm',
  validate
})(MyComponent)
```

The errors are:

```
  ● <ForgotPassword /> › render › should render correctly all

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -37,11 +37,11 @@
                 "canGo": [Function],
                 "createHref": [Function],
                 "entries": Array [
                   Object {
                     "hash": "",
    -                "key": "yhrazi",
    +                "key": "wegq0d",
                     "pathname": "/",
                     "search": "",
                     "state": undefined,
                   },
                 ],
    @@ -51,11 +51,11 @@
                 "index": 0,
                 "length": 1,
                 "listen": [Function],
                 "location": Object {
                   "hash": "",
    -              "key": "yhrazi",
    +              "key": "wegq0d",
                   "pathname": "/",
                   "search": "",
                   "state": undefined,
                 },
                 "push": [Function],
      
      at Object.<anonymous> (tests/renderers/authentication/forgotPassword.tests.js:71:52)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

Am I doing something wrong?

**Comment by adriantoine** [comment] 2017-09-16 12:23
Hi @jpenna,
Thanks for raising the issue, I'll have a look as soon as I can! Sorry for the delay.

**Comment by adriantoine** [comment] 2017-09-17 11:28
It might be due to a key randomly generated by `redux` or `redux-form` but it doesn't look like a bug with `enzyme-to-json`, I'll close this for now, if you need help, please create a small repo to reproduce the issue.

**Closed by adriantoine** 2017-09-17 11:28 UTC
